### PR TITLE
Complete rewrite

### PR DESCRIPTION
**Pull request by Frzk**
This is a rather big PR... I rewrote almost everything.

The main changes are:

- Use of the asyncio Streams API rather than low-level sockets ;
- Less dependencies ;
- Should be easier to handle/manage exceptions;
- Should be easier to write tests ;
- Code is easier to read (IMHO) ;
- Docstrings everywhere ;
- ...

But it also:

- Drops direct support for Python email.message.Message objects ;
- Drops support for STARTTLS (see https://bugs.python.org/issue23749) ;
- Breaks compatibility with previous versions (some methods have been renamed, some have a new signature, some exceptions have been renamed or removed, `debug` mode has been removed, ...)

You can browse the code here : https://github.com/Frzk/smtplibaio

Tell me what you think about it. Of course, I can give further explanations about the decisions I made if you want :-)

### CODE REVIEW

**Comment by hwmrocker** [comment]
wow, this is  a big change :) i don't have the time to review it right now but i will do it on Thursday evening.

**Comment by hwmrocker** [comment]
Wow this code is really nice 😄 
I found one minor issue, you cannot import `SMTP_SSL` from the library directly. There is an import missing in the `__init__.py` file.
I would suggest that the first documention uses SSL, so that it is easier for the people to chose the safer option. But I can do it myself.
The regression with STARTTLS is not that bad, since the normal SSL is safer anyway. We could write a sentence about this in the `README`.

**Comment by Frzk** [comment]
Thanks a lot for your comments !

I've fixed the import issue and the documentation as you suggested.

Regarding the STARTTLS regression, I was thinking about opening an issue with all the details and link to it in the README file. This would also allow us to track it so we can add support for it as soon as possible. What do you think about it ?

**Comment by hwmrocker** [comment]
this sounds great! I will merge it tonight and push a new version to pypi

**Pull request merged**
